0413/instagram/articles/urls.py
from django.urls import path
from . import views

app_name='articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
]

0413/instagram/instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

0413/instagram/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

0413/instagram/articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

0413/instagram/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from . models import Article
from .forms import ArticleForm

# Create your views here.
def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles' : articles
    }
    return render(request, 'articles/index.html', context)

def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save()
            # form.save()
            return redirect('articles:detail', article.pk)
        messages.error(request, 'form 다시 확인 ㄱㄱ')
    else :
        form = ArticleForm()
    context = {
        'form' : form
    }
    return render(request, 'articles/forms.html', context)

def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/detail.html', context)

0413/instagram/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %} {{ article.pk }} 글 {% endblock %}

{% block body %}
    <h1>{{ article.pk }} : {{ article.title }}</h1>
    <p>{{ article.content }}</p>
{% endblock %}

0413/instagram/articles/templates/articles/forms.html
{% extends 'base.html' %}

{% block title %} 새 글쓰기 {% endblock %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <button>작성</button>
    </form>
{% endblock %}

0413/instagram/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block title %} 목록 {% endblock %}

{% block body %}
    {% for article in articles %}
        <p>{{ article.pk }}</p>
        <a href="{% url 'articles:detail' article.pk %}">상세보기</a>
        <hr>
    {% endfor %}
{% endblock %}

0413/instagram/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram - {% block title %} {% endblock %}</title>
</head>
<body>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
    {% block body %}
    {% endblock %}
    <a href="{% url 'articles:index' %}">목록</a>
</body>
</html>