0331/django_crud/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    # /articles/
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),

]

0331/django_crud/django_crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

0331/django_crud/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length = 150)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

0331/django_crud/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles' : articles
    }
    return render(request, 'articles/index.html', context)
    
def new(request):
    return render(request, 'articles/new.html')

def create(request):
    article = Article()
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    # return redirect(f'/articles/')
    return redirect('articles:detail', article.pk)

def detail(request, pk):
    # article = Article.objects.get(id=pk)
    article = get_object_or_404(Article, pk=pk)
    context = {
        'article' : article
    }
    return render(request, 'articles/detail.html', context)

def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.delete()
    return redirect('articles:index')

def edit(request, pk):
    article = get_object_or_404(Article, pk=pk)
    context = {
        'article':article
    }
    return render(request, 'articles/edit.html', context)

def update(reqeust, pk):
    article = get_object_or_404(Article, pk=pk)
    article.title = reqeust.POST.get('title')
    article.content = reqeust.POST.get('content')
    article.save()
    return redirect('articles:detail', article.pk)

0331/django_crud/articles/templates/articles/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>글 작성 완료!</h1>
</body>
</html>

0331/django_crud/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block body %}
    <h1>{{ article.pk }} 번 글</h1>
    <p>Title : {{ article.title }} </p>
    <p>Content : {{article.content}}</p>
    <p>Created : {{article.created_at}}</p>
    <p>Updated : {{article.updated_at}}</p>
    <a href="/articles/">목록 보기 </a>
    <a href="{% url 'articles:delete' article.pk %}">삭제</a>
    <a href="{% url 'articles:edit' article.pk %}">수정</a>
{% endblock %}

0331/django_crud/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block body %}
<h2>{{ article.pk }} 글 수정하기</h2>
<form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    <label for="title">제목 : </label>
    <input type="text" name="title" value="{{ article.title }}" id="title" autofocus required> <br>
    <label for="content">내용 : </label>
    <textarea name="content" id="content">{{ article.content }}</textarea>
    <input type="submit" value="작성완료">
</form>
{% endblock %}

0331/django_crud/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block body %}

    <h2>게시판</h2>
    <a href="{% url 'articles:new' %}"> 글쓰기</a>
    {% for article in articles %}
        <p>ID : {{article.id}}</p>
        <p>Title : {{article.title}}</p>
        <a href="{% url 'articles:detail' article.pk %}">글 보러가기</a>
        <hr>
    {% endfor %}

{% endblock %}

0331/django_crud/articles/templates/articles/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>글쓰기</h1>
    <form action="{% url 'articles:create' %}" method="POST">
        {% csrf_token %}
        <!-- name은 form 에서 필수이다, model의 이름을 그대로 가져오기 -->
        제목 : <input type="text" name="title">
        내용 : <input type="text" name="content">
        <input type="submit" value="작성완료">
    </form>
</body>
</html>