0407/django_form/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('<int:pk>/', views.detail, name='detail'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:pk>/update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
]

0407/django_form/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

0407/django_form/django_form/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

0407/django_form/accounts/models.py
from django.db import models

0407/django_form/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

0407/django_form/accounts/forms.py
# from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

class CustomUserChangeForm(UserChangeForm):
    class Meta :
        model = get_user_model()
        fields = ['username', 'first_name', 'last_name', 'email']

0407/django_form/articles/forms.py
from django import forms
from .models import Article

# class ArticleForm(forms.Form):
#     title = forms.CharField(max_length=100)
#     content = forms.CharField(widget=forms.Textarea)

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        max_length=1,
        label='제목',
        help_text='제목을 입력하세요.',
        widget=forms.TextInput(
            attrs={
                'class': 'my-input',
                'placeholder': '제목입력'
            }
        )
    )
    class Meta:
        model = Article
        fields = ['title', 'content']

0407/django_form/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST

from .forms import CustomUserChangeForm

# Create your views here.
def signup(request):
    # 로그인이 되어 있다면
    if request.user.is_authenticated :
        # 돌아가라....(redirect)
        return redirect('articles:index')

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = UserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)

# 개인 프로필 페이지 느낌
def detail(request, pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=pk)
    context = {
        'user':user
    }
    return render(request, 'accounts/detail.html', context)

def update(request, pk):
    form =CustomUserChangeForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)

def login(request):
    if request.user.is_authenticated :
        return redirect('articles:index')
    if request.method == 'POST' :
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            # 장고 내부 auth.form 에 있는 login 함수를 꺼내쓴다.
            # form.get_user() 은 Authentication 내에 있는 메소드
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else :         
        form = AuthenticationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/login.html', context)

@login_required
def logout(request):
    # 로그인이 되어 있으면 로그아웃하고
    auth_logout(request)
    return redirect('articles:index')

@require_POST
@login_required
def delete(request):
    request.user.delete()
    return redirect('articles:index')

0407/django_form/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .models import Article
from .forms import ArticleForm

# Create your views here.
def index(request):
    # pk의 역순으로 쓰는 order_by('-pk') 그냥 pk 만 쓰면 반대로 
    articles = Article.objects.order_by('-pk')
    context = {
        'articles' : articles
    }
    return render(request, 'articles/index.html', context)

@login_required
def create(request):
    if request.method == 'POST' :
        # POST /articles/new/ => (구) craete 함수
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save()
            return redirect('articles:index')
    
    else :
        # GET /articles/new/
        form = ArticleForm
    #공용 context
    context = {
        'form' : form
    }
    return render(request, 'articles/form.html', context)

def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    context = {
        'article':article
    }
    return render(request, 'articles/detail.html', context)

@require_POST
def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.delete()
    return redirect(f'/articles/')

def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == "POST":
        # instance = article 을 써주면 새 글생성이 아니라 기존 글을 가져와서 수정!
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else :
        # 수정시 해당 article의 instance를 반드시 넘겨줘야 한다.
        form = ArticleForm(instance=article)
    context = {
        'form' : form
    }
    return render(request, 'articles/form.html', context)
    

0407/django_form/accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block body %}
    <h1>{{user.pk}} : {{ user.username }}</h1>
    {% if request.user == user %}
        <form action="{% url 'accounts:delete' %}" method="POST">
            {% csrf_token %}
            <button class= "btn btn-secondary">회원 탈퇴</button>
        </form>
    {% endif %}
    <hr>
{% endblock %}

0407/django_form/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button>로그인</button>
    </form>
{% endblock %}

0407/django_form/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button>회원가입 신청</button>
        <a href="{% url 'accounts:login' %}">로그인</a>
    </form>
{% endblock %}

0407/django_form/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button>회원정보 수정</button>
    </form>
{% endblock %}

0407/django_form/templates/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Live Session</title>
    {% bootstrap_css %}
</head>
<body>
    {% if request.user.is_authenticated %}
        <p>{{request.user.username}}, 님 환영합니다.</p>
        <a href="{% url 'accounts:logout' %}">로그out</a>
    {% else %}
        <a href="{% url 'accounts:login' %}">로그인</a>
        <a href="{% url 'accounts:signup' %}">회원가입</a>
    {% endif %}
    <div class="container">
        {% block body%}
        {% endblock %}
    </div>
    {% bootstrap_javascript jquery='full' %}
</body>
</html>